apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        command:
        - sh
        - -c
        - |
          export BROKER_ID=$(echo ${HOSTNAME} | awk -F'-' '{print $2}')
          echo "Using BROKER_ID: ${BROKER_ID}"
          
          export CLUSTER_ID="lRql9k4TSGOa0f5CEuypzg"
          echo "Using CLUSTER_ID: ${CLUSTER_ID}"
          
          cat > /etc/kafka/kraft/server.properties << EOF
          node.id=${BROKER_ID}
          broker.id=${BROKER_ID}
          process.roles=broker,controller
          controller.quorum.voters=0@kafka-0.kafka:9093,1@kafka-1.kafka:9093,2@kafka-2.kafka:9093
          listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
          listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          controller.listener.names=CONTROLLER
          advertised.listeners=PLAINTEXT://${HOSTNAME}.kafka:9092
          log.dirs=/var/lib/kafka/data
          EOF
          
          kafka-storage format -t ${CLUSTER_ID} -c /etc/kafka/kraft/server.properties
          
          export KAFKA_BROKER_ID=${BROKER_ID}
          export KAFKA_NODE_ID=${BROKER_ID}
          export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${HOSTNAME}.kafka:9092"
          
          exec /etc/confluent/docker/run
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "0@kafka-0.kafka:9093,1@kafka-1.kafka:9093,2@kafka-2.kafka:9093"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "2"
        - name: KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE
          value: "false"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        - name: config
          mountPath: /etc/kafka/kraft
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"
      volumes:
      - name: kafka-data
        emptyDir: {}
      - name: config
        emptyDir: {}